---
- name: Configure crictl
  hosts: k8s_nodes
  become: true
  tasks:
    - name: Create crictl config
      ansible.builtin.copy:
        dest: /etc/crictl.yaml
        content: |
          runtime-endpoint: unix:///run/containerd/containerd.sock
          image-endpoint: unix:///run/containerd/containerd.sock
          timeout: 10
          debug: false
        owner: root
        group: root
        mode: '0644'
