---
# playbook: cni.yml
- hosts: k8s_masters
  become: yes
  tasks:
    - name: Install Flannel CNI
      ansible.builtin.command:
        cmd: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: flannel_result
      changed_when: "'created' in flannel_result.stdout or 'configured' in flannel_result.stdout"
