- name: Regenerate apiserver certificate with external IP
  hosts: k8s_masters
  become: true
  tasks:
    - name: Remove old apiserver certificates
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes/pki/apiserver.crt
        - /etc/kubernetes/pki/apiserver.key

    - name: Regenerate apiserver certificate
      ansible.builtin.command:
        cmd: >
          kubeadm init phase certs apiserver
          --apiserver-cert-extra-sans={{ external_ip }},{{ internal_ip }},{{ inventory_hostname }}


    - name: Restart kube-apiserver
      ansible.builtin.shell: |
        crictl stop $(crictl ps --name kube-apiserver -q)
        crictl rm $(crictl ps -a --name kube-apiserver -q)
      ignore_errors: true

    - name: Wait for kube-apiserver to be ready
      ansible.builtin.wait_for:
        port: 6443
        delay: 5
        timeout: 60

    - name: Fetch updated kubeconfig
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config-vm-1
        flat: yes
